[build]
command = "yarn build"

[build.environment]
NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
deno_import_map = "./netlify/edge-functions/import_map.json"

[dev]
targetPort = 3000

[template.environment]
NODE_VERSION='NODE_VERSION->18.14.0'
NEXT_PUBLIC_DOCS_CHAT_API_URL='NEXT_PUBLIC_DOCS_CHAT_API_URL->/chat'
VECTOR_STORE='VECTOR_STORE->pinecone'
PINECONE_API_KEY='Pinecone API key'
PINECONE_ENVIRONMENT='Pinecone environment'
PINECONE_INDEX_NAME='Pinecone index name'
PINECONE_NAME_SPACE='Pinecone name space'
OPENAI_API_KEY='OpenAI API key'

# Customize UI
NEXT_PUBLIC_HOME_PAGE='Home'
NEXT_PUBLIC_TITLE='Title'
NEXT_PUBLIC_HELLO='Hello'
NEXT_PUBLIC_QUESTION='Question'
NEXT_PUBLIC_WAITING='Waiting'
NEXT_PUBLIC_FOOTER1='Footer 1'
NEXT_PUBLIC_FOOTER2='Footer 2'
NEXT_PUBLIC_FOOTER_LINK='Footer Link'
NEXT_PUBLIC_SOURCE='Source'
NEXT_PUBLIC_URL='URL'
